(()=>{
'use strict';
const BUILD='1.0.0-alpha.3';
const TILE=32, MAP_W=58, MAP_H=38;
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const canvas=$('#game'), ctx=canvas.getContext('2d',{alpha:false});
ctx.imageSmoothingEnabled=false;
const fatal=(error)=>{console.error(error);$('#fatal-message').textContent=String(error&&error.message||error);$('#fatal-error').classList.add('show')};
window.addEventListener('error',e=>fatal(e.error||e.message));
window.addEventListener('unhandledrejection',e=>fatal(e.reason));
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const lerp=(a,b,t)=>a+(b-a)*t;
const key=(x,y)=>`${x},${y}`;
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const hash=(x,y,s=0)=>{let n=(x*374761393+y*668265263+s*1442695041)|0;n=(n^(n>>>13))*1274126177;return ((n^(n>>>16))>>>0)/4294967295};
const makeCanvas=(w,h)=>{const c=document.createElement('canvas');c.width=w;c.height=h;const g=c.getContext('2d');g.imageSmoothingEnabled=false;return [c,g]};
const R=(g,x,y,w,h,c)=>{g.fillStyle=c;g.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h))};
const ellipse=(g,x,y,rx,ry,c)=>{g.fillStyle=c;g.beginPath();g.ellipse(Math.round(x),Math.round(y),rx,ry,0,0,Math.PI*2);g.fill()};
const line=(g,x1,y1,x2,y2,c,w=1)=>{g.strokeStyle=c;g.lineWidth=w;g.beginPath();g.moveTo(x1,y1);g.lineTo(x2,y2);g.stroke()};
const text=(g,s,x,y,size=10,c='#fff',align='center')=>{g.font=`800 ${size}px system-ui`;g.textAlign=align;g.textBaseline='middle';g.fillStyle='#07100ccc';g.fillText(s,x+1,y+1);g.fillStyle=c;g.fillText(s,x,y)};
const HERO_CELL={w:32,h:48};
const HERO_STATES={idle:{start:0,count:4,fps:3},walk:{start:4,count:4,fps:8},staff:{start:8,count:5,fps:12},sling:{start:13,count:5,fps:12},cast:{start:18,count:5,fps:11},hit:{start:23,count:2,fps:8},death:{start:25,count:6,fps:8}};
const HERO_COLS=31;
const [heroAtlas,hg]=makeCanvas(HERO_COLS*HERO_CELL.w,4*HERO_CELL.h);
function drawHeroFrame(g,ox,oy,dir,state,frame){
  const bob=state==='walk'?(frame%2?1:0):state==='idle'?(frame===2?1:0):0;
  const step=state==='walk'?(frame%4===1?2:frame%4===3?-2:0):0;
  const hit=state==='hit',dead=state==='death';
  if(dead){const t=frame/5;ellipse(g,ox+16,oy+42,11,3,'#06100b66');R(g,ox+5,oy+29+t*8,23,9,'#34271f');R(g,ox+8,oy+24+t*9,18,8,'#315b86');R(g,ox+21,oy+21+t*10,9,9,'#e2ad83');R(g,ox+23,oy+18+t*10,8,5,'#4b2d20');return}
  ellipse(g,ox+16,oy+43,10+(state==='staff'?2:0),3,'#07130d88');
  const y=oy+bob;
  const back=dir===0,left=dir===1,right=dir===2,front=dir===3;
  let armSwing=state==='walk'?step:0;
  if(state==='staff')armSwing=frame<3?(-5+frame*4):(14-frame*3);
  R(g,ox+7+(right?3:0),y+23+armSwing/3,6,13,'#274d79');R(g,ox+8+(right?3:0),y+34+armSwing/3,5,5,'#dea77d');
  R(g,ox+10+step,y+34,5,8,'#3a302c');R(g,ox+18-step,y+34,5,8,'#3a302c');R(g,ox+9+step,y+40,7,4,'#241c1a');R(g,ox+17-step,y+40,7,4,'#241c1a');
  R(g,ox+8,y+19,17,17,hit?'#7c3c42':'#315d8d');R(g,ox+9,y+20,5,15,hit?'#9c5054':'#3e70a1');R(g,ox+21,y+21,3,13,'#1c3f67');R(g,ox+8,y+18,17,5,'#172c47');R(g,ox+7,y+20,5,9,'#1b304a');R(g,ox+8,y+32,17,4,'#2b211d');R(g,ox+14,y+31,7,6,'#c89345');R(g,ox+16,y+33,3,2,'#1c1714');
  let fx=right?21:left?5:22,fy=23-armSwing/4;if(state==='sling'){fx=front?24:dir===1?4:22;fy=20-(frame<3?frame*2:(5-frame)*2)}if(state==='cast'){fx=front?23:dir===1?4:22;fy=16-(frame<3?frame:5-frame)}R(g,ox+fx,y+fy,6,13,'#315d8d');R(g,ox+fx+1,y+fy+10,5,5,'#e2aa81');
  R(g,ox+9,y+7,15,13,'#eab58a');R(g,ox+8,y+10,3,8,'#d69771');R(g,ox+22,y+10,3,8,'#d69771');R(g,ox+8,y+4,17,7,'#4a2b20');R(g,ox+6,y+7,6,7,'#563325');R(g,ox+21,y+6,6,8,'#3d241c');R(g,ox+11,y+2,11,5,'#5a3424');R(g,ox+9,y+5,4,3,'#74452f');R(g,ox+15,y+3,4,3,'#70402c');
  if(!back){if(front){R(g,ox+12,y+12,3,3,'#1a1716');R(g,ox+20,y+12,3,3,'#1a1716');R(g,ox+13,y+12,1,1,'#f9f4dc');R(g,ox+21,y+12,1,1,'#f9f4dc')}else if(left){R(g,ox+10,y+12,3,3,'#1a1716');R(g,ox+11,y+12,1,1,'#fff')}else{R(g,ox+21,y+12,3,3,'#1a1716');R(g,ox+22,y+12,1,1,'#fff')}}
  if(state==='staff'){const a=[-1.2,-.7,-.2,.35,.8][frame]||0,cx=ox+16,cy=y+27,len=25;line(g,cx,cy,cx+Math.cos(a)*len,cy+Math.sin(a)*len,'#2a1b13',5);line(g,cx,cy,cx+Math.cos(a)*len,cy+Math.sin(a)*len,'#9b6936',3);ellipse(g,cx+Math.cos(a)*len,cy+Math.sin(a)*len,3,3,'#c18b4d')}
  if(state==='sling'){const px=left?ox+4:right?ox+28:ox+24,py=y+18;line(g,px,py,px+(left?-9:9),py-8,'#d8bd82',2);line(g,px,py,px+(left?-9:9),py+7,'#d8bd82',2);ellipse(g,px+(left?-10:10),py,2,2,'#6f665a')}
  if(state==='cast'){const px=left?ox+3:right?ox+30:ox+27,py=y+17,rr=3+Math.min(frame,3);ellipse(g,px,py,rr+2,rr+2,'#63dcff55');ellipse(g,px,py,rr,rr,'#75e9ff');R(g,px-1,py-2,2,2,'#e8ffff')}
}
for(let dir=0;dir<4;dir++)for(const [state,info] of Object.entries(HERO_STATES))for(let f=0;f<info.count;f++)drawHeroFrame(hg,(info.start+f)*32,dir*48,dir,state,f);
const MON_CELL=40,MON_STATES={idle:{start:0,count:4},walk:{start:4,count:4},attack:{start:8,count:4},hit:{start:12,count:2},death:{start:14,count:5}},MON_COLS=19,MON_TYPES=['gelée','rat','sanglier','loup','feu follet'];
const [monsterAtlas,mg]=makeCanvas(MON_COLS*MON_CELL,MON_TYPES.length*MON_CELL);
function drawMonsterFrame(g,ox,oy,type,state,f){
  const hit=state==='hit',dead=state==='death',walk=state==='walk',attack=state==='attack';if(dead){const t=f/4;ellipse(g,ox+20,oy+33,13*(1-t*.5),4,'#07120d77');R(g,ox+7+t*5,oy+22+t*8,26-t*10,10-t*4,type===0?'#559c5b':type===4?'#5cc9ce':'#5a493f');return}const bob=walk?(f%2?2:0):(f===2?1:0);ellipse(g,ox+20,oy+34,13,4,'#07120d77');
  if(type===0){const c=hit?'#e06b73':'#66bd68';ellipse(g,ox+20,oy+24+bob,14,11+(f%2),c);R(g,ox+9,oy+22+bob,22,11,c);R(g,ox+12,oy+17+bob,7,4,'#8bd783');R(g,ox+14,oy+24+bob,3,3,'#172019');R(g,ox+24,oy+24+bob,3,3,'#172019');R(g,ox+15,oy+24+bob,1,1,'#fff');R(g,ox+25,oy+24+bob,1,1,'#fff');if(attack)R(g,ox+17,oy+29,7,2,'#3a542e')}
  else if(type===1){const c=hit?'#b66b73':'#756861';ellipse(g,ox+20,oy+26+bob,12,8,c);ellipse(g,ox+14,oy+19+bob,8,7,c);ellipse(g,ox+10,oy+14+bob,4,5,'#8a7770');ellipse(g,ox+18,oy+14+bob,4,5,'#8a7770');R(g,ox+10,oy+19+bob,2,2,'#111');R(g,ox+18,oy+19+bob,2,2,'#111');line(g,ox+8,oy+22,ox+2,oy+20,'#bcb1a4',1);line(g,ox+8,oy+24,ox+1,oy+25,'#bcb1a4',1);line(g,ox+30,oy+28,ox+38,oy+24,'#a1887a',2)}
  else if(type===2){const c=hit?'#c4635d':'#85513b';ellipse(g,ox+21,oy+25+bob,14,9,c);R(g,ox+7,oy+20+bob,16,12,c);R(g,ox+9,oy+17+bob,5,5,'#4c2d25');R(g,ox+18,oy+17+bob,5,5,'#4c2d25');ellipse(g,ox+9,oy+28+bob,7,5,'#a26d4d');R(g,ox+6,oy+27+bob,2,2,'#161311');R(g,ox+12,oy+27+bob,2,2,'#161311');R(g,ox+12,oy+21+bob,2,2,'#111');R(g,ox+20,oy+21+bob,2,2,'#111');R(g,ox+13,oy+31,4,5,'#39241e');R(g,ox+26,oy+31,4,5,'#39241e')}
  else if(type===3){const c=hit?'#bd6d77':'#67706a';ellipse(g,ox+21,oy+25+bob,13,8,c);R(g,ox+8,oy+18+bob,14,13,c);R(g,ox+8,oy+12+bob,5,8,'#4d5652');R(g,ox+18,oy+12+bob,5,8,'#4d5652');R(g,ox+11,oy+21+bob,2,2,'#f0dc72');R(g,ox+18,oy+21+bob,2,2,'#f0dc72');R(g,ox+14,oy+27+bob,4,3,'#272b29');line(g,ox+30,oy+24,ox+37,oy+16,'#59615d',4);R(g,ox+13,oy+31,4,5,'#333834');R(g,ox+27,oy+31,4,5,'#333834')}
  else{const c=hit?'#f096a0':'#74d8dd';ellipse(g,ox+20,oy+22+bob,10,12,c+'77');ellipse(g,ox+20,oy+21+bob,7,9,c);ellipse(g,ox+18,oy+18+bob,3,4,'#eaffff');R(g,ox+15,oy+29+bob,3,5,c+'99');R(g,ox+22,oy+29+bob,3,6,c+'99');if(attack){ellipse(g,ox+20,oy+21,14,14,'#9ff8ff33');R(g,ox+19,oy+7,2,4,'#efffff')}}
}
for(let t=0;t<MON_TYPES.length;t++)for(const [s,inf] of Object.entries(MON_STATES))for(let f=0;f<inf.count;f++)drawMonsterFrame(mg,(inf.start+f)*MON_CELL,t*MON_CELL,t,s,f);
const objectSprites={};
function sprite(name,w,h,fn){const [c,g]=makeCanvas(w,h);fn(g,w,h);objectSprites[name]=c}
sprite('treeLarge',80,96,g=>{ellipse(g,40,88,22,5,'#07120d77');R(g,35,55,12,34,'#5e3b23');R(g,39,56,4,32,'#8a5c31');R(g,26,75,28,7,'#4d2f1e');for(const p of [[25,49,23],[44,39,25],[58,56,20],[21,66,18],[45,64,24],[38,22,23]]){ellipse(g,p[0],p[1],p[2],p[2]*.72,'#245c32');ellipse(g,p[0]-3,p[1]-4,p[2]-4,(p[2]-4)*.68,'#3f833d');ellipse(g,p[0]-7,p[1]-8,p[2]-10,(p[2]-10)*.62,'#69a94c')}for(let i=0;i<22;i++){let x=12+hash(i,1)*54,y=13+hash(i,2)*48;R(g,x,y,3,3,hash(i,3)>.7?'#a5cf62':'#4d963f')}});
sprite('treeSmall',58,72,g=>{ellipse(g,29,66,18,4,'#07120d66');R(g,25,42,9,25,'#6c4325');R(g,28,43,3,23,'#9a6234');for(const p of [[19,35,17],[35,27,20],[41,42,15],[23,19,18]]){ellipse(g,p[0],p[1],p[2],p[2]*.7,'#2b6b35');ellipse(g,p[0]-4,p[1]-5,p[2]-5,(p[2]-5)*.65,'#5b9d43')}});
sprite('bush',48,40,g=>{ellipse(g,24,34,18,4,'#07120d66');for(const p of [[13,25,11],[25,20,14],[36,27,10],[22,31,13]]){ellipse(g,p[0],p[1],p[2],p[2]*.7,'#2c6936');ellipse(g,p[0]-3,p[1]-3,p[2]-4,(p[2]-4)*.65,'#589744')}});
sprite('berryBush',50,42,g=>{ellipse(g,25,36,18,4,'#07120d66');for(const p of [[14,26,11],[26,20,14],[38,27,10],[23,32,13]]){ellipse(g,p[0],p[1],p[2],p[2]*.7,'#276234');ellipse(g,p[0]-3,p[1]-3,p[2]-4,(p[2]-4)*.65,'#4e9140')}for(const p of [[16,24],[28,18],[37,28],[23,31],[31,26]])ellipse(g,p[0],p[1],2,2,'#c53248')});
sprite('rock',46,38,g=>{ellipse(g,23,34,17,4,'#07120d66');g.fillStyle='#6f746b';g.beginPath();g.moveTo(7,30);g.lineTo(12,13);g.lineTo(25,6);g.lineTo(38,15);g.lineTo(41,30);g.closePath();g.fill();g.fillStyle='#9b9c8d';g.beginPath();g.moveTo(12,14);g.lineTo(25,7);g.lineTo(27,17);g.lineTo(18,23);g.closePath();g.fill();R(g,31,17,7,12,'#555d58')});
sprite('sign',42,53,g=>{ellipse(g,21,49,11,3,'#07120d77');R(g,18,25,7,25,'#5b351f');R(g,21,26,3,22,'#8b542d');R(g,3,8,36,23,'#6c4124');R(g,6,11,30,17,'#a46b35');R(g,8,14,26,3,'#bd7e42');R(g,31,17,3,3,'#50301d')});
sprite('lamp',38,72,g=>{ellipse(g,19,68,10,3,'#07120d77');R(g,16,29,6,39,'#2e3330');R(g,18,31,2,35,'#6d7168');R(g,14,64,10,5,'#1c2421');line(g,19,31,19,18,'#3e3325',5);line(g,19,19,29,12,'#3e3325',4);R(g,25,10,9,13,'#2b2a22');R(g,27,12,5,8,'#ffd675');R(g,28,13,3,5,'#fff1a5');R(g,25,9,9,3,'#171b18')});
sprite('well',68,56,g=>{ellipse(g,34,48,26,7,'#07120d66');ellipse(g,34,37,25,14,'#696a60');ellipse(g,34,34,21,10,'#9b9a88');ellipse(g,34,35,15,7,'#20353b');for(let x=12;x<58;x+=9)R(g,x,34,3,11,'#555a54');R(g,12,9,5,29,'#6d4327');R(g,51,9,5,29,'#6d4327');line(g,14,12,54,12,'#6d4327',5);R(g,24,8,20,5,'#4d2e20');line(g,34,13,34,26,'#b29a6a',2);R(g,29,24,10,7,'#765039')});
sprite('house',150,130,g=>{ellipse(g,76,121,62,8,'#07120d66');R(g,21,54,110,66,'#b68b58');for(let y=60;y<115;y+=12)line(g,22,y,130,y,'#8f6945',2);R(g,30,67,30,29,'#5f8a82');R(g,35,72,20,19,'#8dc7bd');line(g,45,70,45,94,'#405d5a',3);line(g,32,82,58,82,'#405d5a',3);R(g,91,72,25,48,'#5b3828');R(g,97,79,13,41,'#7b4a2f');ellipse(g,107,97,2,2,'#e3c170');g.fillStyle='#6a3829';g.beginPath();g.moveTo(10,58);g.lineTo(75,10);g.lineTo(141,58);g.closePath();g.fill();g.fillStyle='#934b31';g.beginPath();g.moveTo(16,55);g.lineTo(75,16);g.lineTo(134,55);g.closePath();g.fill();for(let y=29;y<54;y+=8)line(g,25,y,126,y,'#b5613d',3);R(g,111,20,14,32,'#71503a');R(g,108,17,20,7,'#8b684b');R(g,18,116,118,6,'#6e4d34')});
sprite('mentor',38,54,g=>{ellipse(g,19,50,11,3,'#07120d77');R(g,9,21,20,28,'#6c3868');R(g,12,20,14,24,'#8c4a83');R(g,11,8,16,14,'#d8a67f');R(g,8,5,22,7,'#d5c1aa');R(g,6,9,26,5,'#bba48e');R(g,14,14,2,2,'#191615');R(g,23,14,2,2,'#191615');R(g,28,22,4,24,'#513322');ellipse(g,30,19,4,4,'#74d7ec')});
sprite('fenceH',32,28,g=>{R(g,3,7,6,21,'#694025');R(g,24,7,6,21,'#694025');R(g,2,12,29,5,'#986038');R(g,2,21,29,5,'#7f4f30');R(g,5,8,2,17,'#b47742')});
sprite('fenceV',28,32,g=>{R(g,7,3,21,6,'#694025');R(g,7,24,21,6,'#694025');R(g,12,2,5,29,'#986038');R(g,21,2,5,29,'#7f4f30')});
const [iconAtlas,ig]=makeCanvas(4*48,48);function drawWeaponIcon(g,x,type){ellipse(g,x+24,42,15,3,'#07120d55');if(type==='staff'){line(g,x+13,37,x+34,9,'#3b2518',8);line(g,x+13,37,x+34,9,'#a46d35',5);ellipse(g,x+34,9,5,5,'#c7904a');R(g,x+29,6,8,3,'#e0ad64')}if(type==='sling'){line(g,x+14,39,x+25,18,'#7c4c2c',6);line(g,x+25,18,x+17,9,'#c38a4c',4);line(g,x+25,18,x+34,10,'#c38a4c',4);line(g,x+17,9,x+34,10,'#e2d3aa',2);ellipse(g,x+25,20,4,4,'#777268')}if(type==='orb'){ellipse(g,x+24,23,15,15,'#526ee155');ellipse(g,x+24,23,11,11,'#59cde8');ellipse(g,x+21,19,4,4,'#e3ffff');R(g,x+19,36,10,6,'#bd9b59');R(g,x+15,41,18,4,'#6f4b2d')}}drawWeaponIcon(ig,0,'staff');drawWeaponIcon(ig,48,'sling');drawWeaponIcon(ig,96,'orb');
const [portraitAsset,pg]=makeCanvas(64,64);pg.fillStyle='#1b3328';pg.fillRect(0,0,64,64);pg.drawImage(heroAtlas,HERO_STATES.idle.start*32,3*48,32,48,16,7,32,48);R(pg,0,55,64,9,'#0c1a15');
const ASSETS={heroAtlas,monsterAtlas,objectSprites,iconAtlas,portraitAsset};
const blocked=new Set(),objects=[],decorations=[];const [groundCanvas,gg]=makeCanvas(MAP_W*TILE,MAP_H*TILE);const tileType=Array.from({length:MAP_H},()=>Array(MAP_W).fill('grass'));
for(let y=0;y<MAP_H;y++)for(let x=0;x<MAP_W;x++){if((y>=18&&y<=21)||(x>=17&&x<=20))tileType[y][x]='path';if(x>=4&&x<=12&&y>=27&&y<=33){const cx=8,cy=30;if(((x-cx)/5)**2+((y-cy)/4)**2<1)tileType[y][x]='water'}}
function drawGround(){for(let y=0;y<MAP_H;y++)for(let x=0;x<MAP_W;x++){const t=tileType[y][x],px=x*TILE,py=y*TILE,r=hash(x,y);if(t==='grass'){R(gg,px,py,TILE,TILE,r>.66?'#6da349':r>.33?'#659a43':'#719f4c');R(gg,px,py+TILE-2,TILE,2,'#4c7f37');for(let i=0;i<8;i++){let sx=px+2+Math.floor(hash(x*9+i,y,3)*28),sy=py+2+Math.floor(hash(x,y*7+i,4)*27);R(gg,sx,sy,1+(i%2),1,hash(i,x+y)>.5?'#83b75a':'#568b3e')}}else if(t==='path'){R(gg,px,py,TILE,TILE,r>.5?'#b29a67':'#aa9362');R(gg,px,py+TILE-2,TILE,2,'#8d774e');for(let i=0;i<5;i++){let sx=px+3+hash(x+i,y,9)*25,sy=py+3+hash(x,y+i,8)*24;R(gg,sx,sy,2,1,hash(i,x)>.5?'#c6ad78':'#85704a')}if(x>0&&tileType[y][x-1]==='grass')for(let i=0;i<4;i++)R(gg,px,py+i*8,3+hash(x,y,i)*4,5,'#659a43');if(y>0&&tileType[y-1][x]==='grass')for(let i=0;i<4;i++)R(gg,px+i*8,py,5,3+hash(x,y,i+4)*4,'#659a43')}else{R(gg,px,py,TILE,TILE,r>.5?'#3b8392':'#397989');for(let i=0;i<4;i++){let sy=py+6+i*7,off=(x+i+y)%2*5;R(gg,px+off,sy,18,2,'#62a7ae');R(gg,px+22-off,sy+3,8,1,'#79bdbe')}}gg.strokeStyle='#355f2b20';gg.strokeRect(px+.5,py+.5,TILE-1,TILE-1)}for(let y=26;y<=34;y++)for(let x=3;x<=13;x++)if(tileType[y]?.[x]==='grass'&&[[1,0],[-1,0],[0,1],[0,-1]].some(d=>tileType[y+d[1]]?.[x+d[0]]==='water')){let px=x*TILE,py=y*TILE;R(gg,px+4,py+4,24,24,'#8e885d55')}}drawGround();
function occupy(x,y,w=1,h=1){for(let yy=y;yy<y+h;yy++)for(let xx=x;xx<x+w;xx++)blocked.add(key(xx,yy))}function addObject(type,x,y,block=true,meta={}){const spr=objectSprites[type];objects.push({type,x,y,spr,meta});if(block)occupy(x,y,meta.blockW||1,meta.blockH||1)}
for(let x=0;x<MAP_W;x++){blocked.add(key(x,0));blocked.add(key(x,MAP_H-1))}for(let y=0;y<MAP_H;y++){blocked.add(key(0,y));blocked.add(key(MAP_W-1,y))}
const treePositions=[];for(let x=2;x<MAP_W-2;x+=3){if(x<14||x>25)treePositions.push([x,2+(x%2),'treeLarge']);if(x<15||x>24)treePositions.push([x,MAP_H-3-(x%2),'treeLarge'])}for(let y=6;y<MAP_H-5;y+=4){treePositions.push([2+(y%3),y,'treeLarge']);treePositions.push([MAP_W-3-(y%2),y,'treeLarge'])}treePositions.push([6,8,'treeLarge'],[10,6,'treeSmall'],[4,14,'treeLarge'],[9,22,'treeSmall'],[28,5,'treeLarge'],[33,7,'treeSmall'],[49,8,'treeLarge'],[45,15,'treeSmall'],[42,26,'treeLarge'],[50,25,'treeLarge'],[27,30,'treeSmall'],[33,32,'treeLarge'],[6,24,'treeSmall']);for(const [x,y,t] of treePositions)if(tileType[y][x]==='grass')addObject(t,x,y,true);[[13,8],[24,7],[31,12],[40,23],[14,29],[47,20],[35,25],[26,24]].forEach((p,i)=>addObject(i%2?'berryBush':'bush',...p,true));[[12,13],[25,10],[32,24],[46,12],[38,30],[14,25],[51,18]].forEach(p=>addObject('rock',...p,true));
addObject('house',42,8,true,{blockW:4,blockH:3});occupy(42,8,4,3);addObject('well',36,13,true,{blockW:2,blockH:1});addObject('sign',22,18,true);addObject('lamp',23,21,true);addObject('lamp',39,20,true);for(let x=34;x<=48;x++)if(x!==40)addObject('fenceH',x,17,true);for(let y=9;y<=16;y++)addObject('fenceV',49,y,true);addObject('mentor',38,16,true,{mentor:'Épéiste'});addObject('mentor',40,16,true,{mentor:'Archer'});addObject('mentor',42,16,true,{mentor:'Mage'});
for(let i=0;i<130;i++){let x=2+Math.floor(hash(i,1)*54),y=3+Math.floor(hash(i,2)*32);if(tileType[y][x]==='grass'&&!blocked.has(key(x,y))){let r=hash(i,3);decorations.push({x:x*TILE+5+hash(i,4)*22,y:y*TILE+7+hash(i,5)*20,type:r>.76?'flower':r>.42?'tuft':'speck',variant:Math.floor(hash(i,6)*3)})}}for(let x=3;x<55;x+=4)if(tileType[20][x]==='path')decorations.push({x:x*TILE+8,y:20*TILE+18,type:'stone',variant:x%3});
const spawn={x:18,y:16};const defaultSave={name:'Voyageur 801',level:1,xp:0,className:'Aventurier',classLevel:1,classXp:0,speed:100,hp:100,maxHp:100,mp:40,maxMp:40,gold:0,weapon:'staff',masteries:{melee:{level:1,xp:0},ranged:{level:1,xp:0},magic:{level:1,xp:0},defense:{level:1,xp:0}},inventory:{Potion:2,'Peau de gelée':0,'Fourrure':0,'Éclat magique':0},equipment:{weapon:'Bâton usé',armor:'Tunique de voyageur'}};let stored=null;try{if(!new URLSearchParams(location.search).has('reset'))stored=JSON.parse(localStorage.getItem('solenne-alpha3')||'null')}catch{}const save=Object.assign({},defaultSave,stored||{});save.masteries=Object.assign({},defaultSave.masteries,stored?.masteries||{});for(const k of Object.keys(defaultSave.masteries))save.masteries[k]=Object.assign({},defaultSave.masteries[k],stored?.masteries?.[k]||{});save.inventory=Object.assign({},defaultSave.inventory,stored?.inventory||{});save.equipment=Object.assign({},defaultSave.equipment,stored?.equipment||{});const player={...save,x:spawn.x,y:spawn.y,rx:spawn.x,ry:spawn.y,path:[],step:null,state:'idle',dir:3,anim:0,actionTime:0,attackCooldown:0,dead:false,respawnTime:0,flash:0};
const monsterDefs=[{type:0,name:'Gelée des prés',level:1,x:24,y:15,maxHp:34,damage:3,xp:28,classXp:18,gold:[2,6],loot:'Peau de gelée'},{type:1,name:'Rat des champs',level:1,x:28,y:22,maxHp:28,damage:3,xp:24,classXp:16,gold:[1,4],loot:'Fourrure'},{type:2,name:'Sanglier brun',level:3,x:15,y:25,maxHp:72,damage:7,xp:55,classXp:34,gold:[5,11],loot:'Cuir robuste'},{type:3,name:'Loup gris',level:4,x:31,y:15,maxHp:86,damage:9,xp:68,classXp:42,gold:[7,14],loot:'Fourrure'},{type:4,name:'Feu follet',level:5,x:11,y:16,maxHp:76,damage:10,xp:78,classXp:50,gold:[9,17],loot:'Éclat magique'}];const monsters=monsterDefs.map((d,id)=>({...d,id,hp:d.maxHp,rx:d.x,ry:d.y,path:[],step:null,state:'idle',anim:0,attackCooldown:Math.random(),actionTime:0,dead:false,respawn:0,flash:0,wander:1+Math.random()*3}));const projectiles=[],particles=[],floaters=[];let target=null,selectedTile=null,camera={x:0,y:0},view={w:960,h:540,scale:1},last=performance.now(),autosave=0,toastTimer=0;
const dirs=[[1,0],[-1,0],[0,1],[0,-1]];function isWalkable(x,y,ignoreMonster=null){if(x<1||y<1||x>=MAP_W-1||y>=MAP_H-1||blocked.has(key(x,y))||tileType[y]?.[x]==='water')return false;return !monsters.some(m=>m!==ignoreMonster&&!m.dead&&m.x===x&&m.y===y)}function pathfind(start,goal,range=0,ignoreMonster=null){const open=[{x:start.x,y:start.y,g:0,f:0}],came=new Map(),costs=new Map([[key(start.x,start.y),0]]);let loops=0,end=null;while(open.length&&loops++<1800){open.sort((a,b)=>a.f-b.f);const cur=open.shift();if(Math.abs(cur.x-goal.x)+Math.abs(cur.y-goal.y)<=range){end=cur;break}for(const [dx,dy] of dirs){const nx=cur.x+dx,ny=cur.y+dy,k=key(nx,ny);if(!isWalkable(nx,ny,ignoreMonster)&&!(nx===goal.x&&ny===goal.y&&range===0))continue;const ng=cur.g+1;if(ng<(costs.get(k)??Infinity)){costs.set(k,ng);came.set(k,cur);open.push({x:nx,y:ny,g:ng,f:ng+Math.abs(nx-goal.x)+Math.abs(ny-goal.y)})}}}const out=[];while(end&&!(end.x===start.x&&end.y===start.y)){out.push({x:end.x,y:end.y});end=came.get(key(end.x,end.y))}return out.reverse()}function setPath(entity,path){entity.path=path;entity.step=null}function updateMovement(entity,dt,speed=100){if(!entity.step&&entity.path.length){const next=entity.path.shift();entity.step={fromX:entity.x,fromY:entity.y,toX:next.x,toY:next.y,t:0};const dx=next.x-entity.x,dy=next.y-entity.y;entity.dir=Math.abs(dx)>Math.abs(dy)?(dx<0?1:2):(dy<0?0:3)}if(entity.step){const duration=.27*100/speed;entity.step.t+=dt/duration;const t=clamp(entity.step.t,0,1),smooth=t*t*(3-2*t);entity.rx=lerp(entity.step.fromX,entity.step.toX,smooth);entity.ry=lerp(entity.step.fromY,entity.step.toY,smooth);entity.state='walk';if(t>=1){entity.x=entity.step.toX;entity.y=entity.step.toY;entity.rx=entity.x;entity.ry=entity.y;entity.step=null}}}
const WEAPONS={staff:{label:'Bâton',range:1.25,cooldown:.72,mana:0,damage:[7,11],mastery:'melee',state:'staff'},sling:{label:'Fronde',range:5.3,cooldown:.88,mana:0,damage:[6,9],mastery:'ranged',state:'sling'},orb:{label:'Orbe',range:5.1,cooldown:1,mana:4,damage:[9,14],mastery:'magic',state:'cast'}};const xpNeed=l=>100+l*35,classNeed=l=>70+l*30,masteryNeed=l=>35+l*22;function gainMastery(type,amount){const m=player.masteries[type];m.xp+=amount;while(m.xp>=masteryNeed(m.level)){m.xp-=masteryNeed(m.level);m.level++;showToast(`${type==='melee'?'Corps à corps':type==='ranged'?'Distance':type==='magic'?'Magie':'Défense'} passe niveau ${m.level}`)}}function addFloater(x,y,value,color='#fff'){floaters.push({x,y,value:String(value),color,life:1})}function burst(x,y,color,count=9){for(let i=0;i<count;i++){const a=Math.PI*2*i/count+Math.random()*.4,s=18+Math.random()*42;particles.push({x:x*TILE+TILE/2,y:y*TILE+TILE/2,vx:Math.cos(a)*s,vy:Math.sin(a)*s-15,life:.45+Math.random()*.4,color,size:2+Math.random()*3})}}
function dealDamage(m){const w=WEAPONS[player.weapon],mastery=player.masteries[w.mastery].level;let amount=Math.floor(w.damage[0]+Math.random()*(w.damage[1]-w.damage[0]+1)+mastery*.35);m.hp=Math.max(0,m.hp-amount);m.flash=.16;m.state='hit';m.actionTime=.22;gainMastery(w.mastery,3+Math.random()*2);addFloater(m.rx,m.ry-.7,amount,'#ffe4a1');burst(m.rx,m.ry,player.weapon==='orb'?'#71e4ff':player.weapon==='sling'?'#d6c5a0':'#f2bb73',7);if(m.hp<=0)killMonster(m)}function fireAttack(m){const w=WEAPONS[player.weapon];if(player.attackCooldown>0||player.actionTime>0||player.mp<w.mana||player.dead)return;player.mp-=w.mana;player.attackCooldown=w.cooldown;player.actionTime=player.weapon==='staff'?.42:.5;player.state=w.state;player.anim=0;const dx=m.rx-player.rx,dy=m.ry-player.ry;player.dir=Math.abs(dx)>Math.abs(dy)?(dx<0?1:2):(dy<0?0:3);if(player.weapon==='staff')setTimeout(()=>{if(!m.dead&&dist(player,m)<=w.range+.45)dealDamage(m)},170);else projectiles.push({type:player.weapon,x:player.rx+.5,y:player.ry+.45,target:m,speed:player.weapon==='orb'?8:11,life:2})}
function killMonster(m){m.dead=true;m.state='death';m.actionTime=.65;m.respawn=8+Math.random()*5;player.xp+=m.xp;player.classXp+=m.classXp;const gold=m.gold[0]+Math.floor(Math.random()*(m.gold[1]-m.gold[0]+1));player.gold+=gold;addFloater(m.rx,m.ry-1.1,`+${m.xp} XP`,'#ffe28b');addFloater(m.rx,m.ry-.5,`+${gold} or`,'#ffd05e');if(Math.random()<.38){player.inventory[m.loot]=(player.inventory[m.loot]||0)+1;showToast(`${m.loot} obtenu`)}if(Math.random()<.13){player.inventory['Bottes de pisteur']=(player.inventory['Bottes de pisteur']||0)+1;showToast('Équipement rare : Bottes de pisteur')}target=null;checkLevels();saveGame()}function checkLevels(){while(player.xp>=xpNeed(player.level)){player.xp-=xpNeed(player.level);player.level++;player.speed=99+player.level;player.maxHp+=8;player.maxMp+=2;player.hp=player.maxHp;player.mp=player.maxMp;showToast(`Niveau général ${player.level} !`);burst(player.rx,player.ry,'#ffe48a',18)}while(player.classXp>=classNeed(player.classLevel)){player.classXp-=classNeed(player.classLevel);player.classLevel++;showToast(`${player.className} rang ${player.classLevel}`)}}
function monsterAttack(m){if(m.attackCooldown>0||m.actionTime>0||player.dead)return;m.attackCooldown=1.3;m.actionTime=.35;m.state='attack';setTimeout(()=>{if(!m.dead&&!player.dead&&dist(m,player)<1.6){const dmg=m.damage+Math.floor(Math.random()*3);player.hp=Math.max(0,player.hp-dmg);player.flash=.18;player.state='hit';player.actionTime=.22;gainMastery('defense',2.5+Math.random()*2);addFloater(player.rx,player.ry-.8,dmg,'#ff9b95');burst(player.rx,player.ry,'#ef8277',6);if(player.hp<=0)die()}},180)}function die(){player.dead=true;player.state='death';player.anim=0;player.path=[];player.step=null;player.respawnTime=2.6;target=null;showToast('Vous avez été vaincu… retour au village')}function respawn(){player.dead=false;player.x=spawn.x;player.y=spawn.y;player.rx=spawn.x;player.ry=spawn.y;player.hp=player.maxHp;player.mp=player.maxMp;player.state='idle';burst(player.rx,player.ry,'#a7f7cb',18)}
let toastEl=document.createElement('div');toastEl.className='toast';$('#game-shell').append(toastEl);function showToast(message){toastEl.textContent=message;toastEl.classList.add('show');toastTimer=2.3}function syncUI(){$('#player-name').textContent=player.name;$('#general-level').textContent=player.level;$('#class-name').textContent=player.className;$('#class-level').textContent=player.classLevel;$('#hp-text').textContent=`${Math.ceil(player.hp)}/${player.maxHp}`;$('#mp-text').textContent=`${Math.floor(player.mp)}/${player.maxMp}`;$('#hp-bar').style.width=`${100*player.hp/player.maxHp}%`;$('#mp-bar').style.width=`${100*player.mp/player.maxMp}%`;$('#xp-text').textContent=`${Math.floor(player.xp)}/${xpNeed(player.level)}`;$('#class-xp-text').textContent=`${Math.floor(player.classXp)}/${classNeed(player.classLevel)}`;$('#xp-bar').style.width=`${100*player.xp/xpNeed(player.level)}%`;$('#class-xp-bar').style.width=`${100*player.classXp/classNeed(player.classLevel)}%`;$('#gold-text').textContent=player.gold;$('#potion-count').textContent=player.inventory.Potion||0;$('#inventory-count').textContent=Object.values(player.inventory).reduce((a,b)=>a+b,0);$$('.weapon-button').forEach(b=>b.classList.toggle('selected',b.dataset.weapon===player.weapon));if(target&&!target.dead){$('#target-card').classList.add('visible');$('#target-name').textContent=target.name;$('#target-level').textContent=`Niv. ${target.level}`;$('#target-hp-bar').style.width=`${100*target.hp/target.maxHp}%`;$('#world-hint-text').textContent=`Cible : ${target.name}`}else{$('#target-card').classList.remove('visible');$('#world-hint-text').textContent='Touchez une case ou un monstre'}}
function renderStats(){const names={melee:'Corps à corps',ranged:'Distance',magic:'Magie',defense:'Défense'};return `<div class="stat-grid">${Object.entries(player.masteries).map(([k,m])=>`<article class="stat-card"><small>${names[k]}</small><b>${m.level}</b><progress max="${masteryNeed(m.level)}" value="${m.xp}"></progress><small>${Math.floor(m.xp)} / ${masteryNeed(m.level)} XP</small></article>`).join('')}<article class="stat-card"><small>Vitesse</small><b>${player.speed}</b><small>+1 par niveau général</small></article><article class="stat-card"><small>Classe</small><b>${player.classLevel}</b><small>${player.className}</small></article></div><div class="equipment-row"><article class="equipment-card"><small>Arme équipée</small><b>${player.equipment.weapon}</b></article><article class="equipment-card"><small>Armure</small><b>${player.equipment.armor}</b></article></div><article class="info-card"><b>Évolution de classe</b><p>${player.className==='Aventurier'?`Parlez à un mentor au rang 20 pour devenir Épéiste, Archer ou Mage. Le choix sera permanent.`:`Votre voie de ${player.className} est permanente. De nouvelles évolutions seront disponibles à haut rang.`}</p></article>`}function renderInventory(){const descriptions={Potion:'Restaure 45 PV.','Peau de gelée':'Matériau souple et translucide.','Fourrure':'Matériau obtenu sur les bêtes.','Éclat magique':'Fragment chargé de mana.','Cuir robuste':'Matériau résistant.','Bottes de pisteur':'+1 défense, équipement rare.'};return `<div class="inventory-list">${Object.entries(player.inventory).filter(([,v])=>v>0).map(([k,v])=>`<article class="inventory-item"><span class="item-icon"><span class="item-pixel"></span></span><div><b>${k}</b><small>${descriptions[k]||'Objet d’aventure.'}</small></div><span>x${v}</span></article>`).join('')||'<p>Votre sac est vide.</p>'}</div><div class="equipment-row"><article class="equipment-card"><small>Arme</small><b>${player.equipment.weapon}</b></article><article class="equipment-card"><small>Armure</small><b>${player.equipment.armor}</b></article></div>`}
function openDrawer(type){const d=$('#drawer');$('#drawer-kicker').textContent=type==='stats'?'Progression':type==='inventory'?'Sac de voyage':'Options';$('#drawer-title').textContent=type==='stats'?'Statistiques':type==='inventory'?'Inventaire':'Paramètres';$('#drawer-content').innerHTML=type==='stats'?renderStats():type==='inventory'?renderInventory():`<article class="info-card"><b>Chroniques de Solenne</b><p>Build ${BUILD}</p><p>Mode paysage · déplacement tactile case par case · sauvegarde locale active.</p><button class="secondary-button" id="reset-save">Réinitialiser la sauvegarde</button></article>`;d.classList.add('open');d.setAttribute('aria-hidden','false');$('#drawer-backdrop').classList.add('open');if(type==='settings')setTimeout(()=>$('#reset-save')?.addEventListener('click',()=>{localStorage.removeItem('solenne-alpha3');location.href=location.pathname+'?reset=1'}),0)}function closeDrawer(){$('#drawer').classList.remove('open');$('#drawer').setAttribute('aria-hidden','true');$('#drawer-backdrop').classList.remove('open')}
$('#stats-button').addEventListener('click',()=>openDrawer('stats'));$('#inventory-button').addEventListener('click',()=>openDrawer('inventory'));$('#settings-button').addEventListener('click',()=>openDrawer('settings'));$('#drawer-close').addEventListener('click',closeDrawer);$('#drawer-backdrop').addEventListener('click',closeDrawer);$$('.weapon-button').forEach((b,i)=>{b.addEventListener('click',()=>{player.weapon=b.dataset.weapon;syncUI();saveGame()});const cg=b.querySelector('canvas').getContext('2d');cg.imageSmoothingEnabled=false;cg.drawImage(iconAtlas,i*48,0,48,48,0,0,48,48)});$('#potion-button').addEventListener('click',()=>{if((player.inventory.Potion||0)>0&&player.hp<player.maxHp){player.inventory.Potion--;player.hp=Math.min(player.maxHp,player.hp+45);burst(player.rx,player.ry,'#82e894',12);showToast('Potion utilisée : +45 PV');saveGame()}else showToast(player.hp>=player.maxHp?'Vos PV sont déjà au maximum':'Vous n’avez plus de potion')});$('#portrait').getContext('2d').drawImage(portraitAsset,0,0,64,64);$('#class-cancel').addEventListener('click',()=>$('#class-modal').classList.remove('open'));$$('[data-class]').forEach(b=>b.addEventListener('click',()=>{if(player.className!=='Aventurier'||player.classLevel<20)return;player.className=b.dataset.class;player.classLevel=1;player.classXp=0;$('#class-modal').classList.remove('open');showToast(`Vous êtes désormais ${player.className}`);saveGame();syncUI()}));function saveGame(){const out={};for(const k of Object.keys(defaultSave))out[k]=player[k];try{localStorage.setItem('solenne-alpha3',JSON.stringify(out))}catch{}}
function screenToWorld(clientX,clientY){const r=canvas.getBoundingClientRect(),sx=(clientX-r.left)/r.width*view.w,sy=(clientY-r.top)/r.height*view.h;return{x:(sx+camera.x)/TILE,y:(sy+camera.y)/TILE}}function selectMonster(m){if(m.dead)return;target=m;selectedTile={x:m.x,y:m.y};const w=WEAPONS[player.weapon];setPath(player,pathfind(player,m,Math.max(1,Math.floor(w.range)),m));syncUI()}canvas.addEventListener('pointerdown',e=>{e.preventDefault();if(player.dead)return;const p=screenToWorld(e.clientX,e.clientY),m=monsters.filter(m=>!m.dead).sort((a,b)=>dist(a,p)-dist(b,p))[0];if(m&&dist(m,p)<.8){selectMonster(m);return}const gx=Math.floor(p.x),gy=Math.floor(p.y),mentor=objects.find(o=>o.meta.mentor&&Math.hypot(o.x-gx,o.y-gy)<1.2);if(mentor){if(player.className==='Aventurier'&&player.classLevel>=20)$('#class-modal').classList.add('open');else showToast(player.className!=='Aventurier'?`Vous suivez déjà la voie ${player.className}`:'Revenez au rang Aventurier 20');return}target=null;selectedTile={x:gx,y:gy};if(isWalkable(gx,gy))setPath(player,pathfind(player,{x:gx,y:gy}));syncUI()},{passive:false});
function updatePlayer(dt){player.attackCooldown=Math.max(0,player.attackCooldown-dt);player.actionTime=Math.max(0,player.actionTime-dt);player.flash=Math.max(0,player.flash-dt);player.mp=Math.min(player.maxMp,player.mp+dt*1.4);if(player.dead){player.respawnTime-=dt;player.anim+=dt;if(player.respawnTime<=0)respawn();return}updateMovement(player,dt,player.speed);if(target&&!target.dead){const w=WEAPONS[player.weapon],d=dist(player,target);if(!player.step&&!player.path.length&&d>w.range+.15)setPath(player,pathfind(player,target,Math.max(1,Math.floor(w.range)),target));if(d<=w.range+.12&&!player.step)fireAttack(target)}if(player.actionTime<=0)player.state=(player.step||player.path.length)?'walk':'idle';player.anim+=dt}function updateMonster(m,dt){if(m.dead){m.respawn-=dt;m.anim+=dt;if(m.respawn<=0){m.dead=false;m.hp=m.maxHp;m.rx=m.x;m.ry=m.y;m.state='idle';m.anim=0}return}m.attackCooldown=Math.max(0,m.attackCooldown-dt);m.actionTime=Math.max(0,m.actionTime-dt);m.flash=Math.max(0,m.flash-dt);m.wander-=dt;const d=dist(m,player);if(!player.dead&&d<4.5&&d>1.2&&!m.step&&!m.path.length)setPath(m,pathfind(m,player,1,m));else if(!player.dead&&d<=1.25)monsterAttack(m);else if(m.wander<=0&&!m.step&&!m.path.length){m.wander=2+Math.random()*4;const gx=clamp(m.x+Math.floor(Math.random()*7)-3,1,MAP_W-2),gy=clamp(m.y+Math.floor(Math.random()*7)-3,1,MAP_H-2);if(isWalkable(gx,gy,m))setPath(m,pathfind(m,{x:gx,y:gy},0,m).slice(0,4))}updateMovement(m,dt,76+m.level*2);if(m.actionTime<=0)m.state=(m.step||m.path.length)?'walk':'idle';m.anim+=dt}function updateProjectiles(dt){for(let i=projectiles.length-1;i>=0;i--){const p=projectiles[i];p.life-=dt;if(p.target.dead||p.life<=0){projectiles.splice(i,1);continue}const tx=p.target.rx+.5,ty=p.target.ry+.5,dx=tx-p.x,dy=ty-p.y,d=Math.hypot(dx,dy),step=p.speed*dt;if(d<=step+.1){dealDamage(p.target);projectiles.splice(i,1)}else{p.x+=dx/d*step;p.y+=dy/d*step;if(p.type==='orb'&&Math.random()<.7)particles.push({x:p.x*TILE,y:p.y*TILE,vx:(Math.random()-.5)*8,vy:(Math.random()-.5)*8,life:.25,color:'#8cecff',size:2})}}}function updateEffects(dt){for(let i=particles.length-1;i>=0;i--){let p=particles[i];p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=35*dt;if(p.life<=0)particles.splice(i,1)}for(let i=floaters.length-1;i>=0;i--){let f=floaters[i];f.life-=dt;f.y-=dt*.55;if(f.life<=0)floaters.splice(i,1)}if(toastTimer>0){toastTimer-=dt;if(toastTimer<=0)toastEl.classList.remove('show')}}function update(dt){updatePlayer(dt);for(const m of monsters)updateMonster(m,dt);updateProjectiles(dt);updateEffects(dt);checkLevels();camera.x=lerp(camera.x,clamp(player.rx*TILE-view.w/2,0,MAP_W*TILE-view.w),.11);camera.y=lerp(camera.y,clamp(player.ry*TILE-view.h/2,0,MAP_H*TILE-view.h),.11);autosave+=dt;if(autosave>8){autosave=0;saveGame()}syncUI()}
function frameIndex(state,anim){const info=HERO_STATES[state]||HERO_STATES.idle;return info.start+Math.floor(anim*info.fps)%info.count}function monFrame(m){const info=MON_STATES[m.state]||MON_STATES.idle;return info.start+Math.floor(m.anim*(m.state==='walk'?8:5))%info.count}function drawDecoration(d){const x=d.x-camera.x,y=d.y-camera.y;if(x<-10||y<-10||x>view.w+10||y>view.h+10)return;if(d.type==='flower'){const colors=['#fff4ce','#ef7e91','#a795ef'];R(ctx,x-1,y-3,2,7,'#3a7a35');R(ctx,x-4,y-2,3,3,colors[d.variant]);R(ctx,x+2,y-2,3,3,colors[d.variant]);R(ctx,x-1,y-5,3,3,colors[d.variant]);R(ctx,x-1,y-1,2,2,'#ffd566')}else if(d.type==='tuft'){line(ctx,x,y+4,x-3,y-4,'#397f36',2);line(ctx,x,y+4,x+2,y-6,'#4b913c',2);line(ctx,x,y+4,x+5,y-2,'#347533',2)}else if(d.type==='stone'){ellipse(ctx,x,y,4,2,'#77786d');R(ctx,x-2,y-2,4,2,'#a0a08e')}else R(ctx,x,y,1,1,'#9fc56c')}function drawObject(o){const x=o.x*TILE-camera.x,y=o.y*TILE-camera.y,s=o.spr;let ax=s.width/2-TILE/2,ay=s.height-TILE;if(o.type==='house'){ax=10;ay=s.height-3*TILE}else if(o.type==='fenceH'||o.type==='fenceV'){ax=0;ay=s.height-TILE}else if(o.type==='well'){ax=s.width/2-TILE/2;ay=s.height-TILE}ctx.drawImage(s,Math.round(x-ax),Math.round(y-ay));if(o.meta.mentor)text(ctx,o.meta.mentor,x+16,y-ay-7,9,'#ffe6a1')}
function drawEntity(e,isPlayer=false){const x=e.rx*TILE-camera.x,y=e.ry*TILE-camera.y;if(isPlayer){if(target||selectedTile){ellipse(ctx,x+16,y+30,16,6,'#f4d36a33');ctx.strokeStyle='#f0cf68';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(x+16,y+30,16,6,0,0,Math.PI*2);ctx.stroke()}const frame=frameIndex(e.state,e.anim);ctx.save();if(e.flash>0)ctx.globalAlpha=.45;ctx.drawImage(heroAtlas,frame*32,e.dir*48,32,48,Math.round(x),Math.round(y-17),32,48);ctx.restore();text(ctx,`${player.name} · Niv. ${player.level}`,x+16,y-29,10,'#fff')}else{const frame=monFrame(e);ctx.save();if(e.flash>0)ctx.globalAlpha=.45;ctx.drawImage(monsterAtlas,frame*40,e.type*40,40,40,Math.round(x-4),Math.round(y-9),40,40);ctx.restore();text(ctx,`${e.name} · ${e.level}`,x+16,y-19,9,target===e?'#ffe394':'#edf2e9');if(e.hp<e.maxHp||target===e){R(ctx,x+3,y-11,26,4,'#180b0b');R(ctx,x+4,y-10,24*e.hp/e.maxHp,2,'#e5524b')}if(target===e){ctx.strokeStyle='#f1d36b';ctx.lineWidth=2;ctx.strokeRect(Math.round(x-5),Math.round(y-10),42,42)}}}
function draw(){ctx.setTransform(view.scale,0,0,view.scale,0,0);ctx.imageSmoothingEnabled=false;R(ctx,0,0,view.w,view.h,'#375f32');ctx.drawImage(groundCanvas,Math.floor(camera.x),Math.floor(camera.y),view.w,view.h,0,0,view.w,view.h);for(const d of decorations)drawDecoration(d);if(selectedTile){const sx=selectedTile.x*TILE-camera.x,sy=selectedTile.y*TILE-camera.y;ctx.strokeStyle='#f5df8b99';ctx.lineWidth=2;ctx.strokeRect(Math.round(sx+2),Math.round(sy+2),TILE-4,TILE-4)}if(player.path.length){for(let i=0;i<Math.min(player.path.length,12);i++){const p=player.path[i],x=p.x*TILE+16-camera.x,y=p.y*TILE+16-camera.y;ellipse(ctx,x,y,2.5,2.5,`rgba(255,232,143,${.55-i*.03})`)}}const drawables=[];for(const o of objects)drawables.push({y:o.y+.9,kind:'object',o});for(const m of monsters)if(!m.dead||m.state==='death')drawables.push({y:m.ry+.7,kind:'monster',m});drawables.push({y:player.ry+.72,kind:'player'});drawables.sort((a,b)=>a.y-b.y);for(const d of drawables){if(d.kind==='object')drawObject(d.o);else if(d.kind==='monster')drawEntity(d.m,false);else drawEntity(player,true)}for(const p of projectiles){const x=p.x*TILE-camera.x,y=p.y*TILE-camera.y;if(p.type==='orb'){ellipse(ctx,x,y,7,7,'#5ccfe066');ellipse(ctx,x,y,4,4,'#9ff5ff');R(ctx,x-1,y-2,2,2,'#fff')}else{ellipse(ctx,x,y,3,3,'#77746d');line(ctx,x-5,y+2,x+3,y-2,'#dbd0b6',1)}}for(const p of particles){ctx.globalAlpha=clamp(p.life*2,0,1);R(ctx,p.x-camera.x,p.y-camera.y,p.size,p.size,p.color)}ctx.globalAlpha=1;for(const f of floaters){ctx.globalAlpha=clamp(f.life*1.8,0,1);text(ctx,f.value,f.x*TILE+16-camera.x,f.y*TILE-camera.y,10,f.color)}ctx.globalAlpha=1;const grad=ctx.createRadialGradient(view.w/2,view.h/2,view.h*.25,view.w/2,view.h/2,view.w*.7);grad.addColorStop(0,'#0000');grad.addColorStop(1,'#07100b38');ctx.fillStyle=grad;ctx.fillRect(0,0,view.w,view.h)}function resize(){const r=canvas.getBoundingClientRect(),dpr=Math.min(window.devicePixelRatio||1,2);view.h=540;view.w=clamp(Math.round(view.h*r.width/r.height),900,1240);view.scale=Math.min(r.width/view.w,r.height/view.h)*dpr;canvas.width=Math.round(view.w*view.scale);canvas.height=Math.round(view.h*view.scale);ctx.imageSmoothingEnabled=false;draw()}window.addEventListener('resize',resize);window.addEventListener('orientationchange',()=>setTimeout(resize,120));
function snapshot(){return{build:BUILD,player:{x:player.x,y:player.y,rx:+player.rx.toFixed(2),ry:+player.ry.toFixed(2),level:player.level,className:player.className,classLevel:player.classLevel,hp:player.hp,mp:+player.mp.toFixed(1),gold:player.gold,weapon:player.weapon,state:player.state,speed:player.speed,masteries:player.masteries},target:target?{id:target.id,name:target.name,hp:target.hp,dead:target.dead}:null,monsters:monsters.map(m=>({id:m.id,name:m.name,x:m.x,y:m.y,hp:m.hp,dead:m.dead,state:m.state})),camera:{x:+camera.x.toFixed(1),y:+camera.y.toFixed(1)},view:{...view},assets:{heroFrames:HERO_COLS*4,monsterFrames:MON_COLS*MON_TYPES.length,objects:Object.keys(objectSprites).length,build:BUILD}}}window.__SOLENNE__={build:BUILD,assets:{heroAtlas,monsterAtlas,iconAtlas,portraitAsset,objects:Object.keys(objectSprites)},debug:{snapshot,selectMonster:(id=0)=>selectMonster(monsters[id]),teleport:(x,y)=>{if(isWalkable(x,y)){player.x=x;player.y=y;player.rx=x;player.ry=y;player.path=[];player.step=null}},damageMonster:(id=0,n=999)=>{const m=monsters[id];m.hp=Math.max(0,m.hp-n);if(m.hp<=0)killMonster(m)},setClassLevel:n=>{player.classLevel=n;syncUI()},reset:()=>{localStorage.removeItem('solenne-alpha3');location.reload()}}};resize();syncUI();function loop(now){const dt=Math.min(.05,(now-last)/1000||0);last=now;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);window.__SOLENNE__.ready=true;
})()
